# Generated by Django 4.2.4 on 2023-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=350)),
                ('imgs', models.ImageField(upload_to='photos')),
                ('desc', models.TextField()),
            ],
        ),
    ]
